In [8]:
import pandas as pd
from sklearn.model_selection import KFold , StratifiedKFold, cross_val_score
from sklearn.ensemble import GradientBoostingClassifier

import warnings
warnings.filterwarnings('ignore')

In [9]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\pizza.csv")
df.sample(5)

    Promote  Sales
12       71   1750
2        34    815
1        56   1339
17       90   2000
15       44   1000

In [10]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Vehicle Silhouettes\Vehicle.csv")
df.sample(5)

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
164,98,54,104,186,59,10,213,32,24,172,223,665,217,73,1,26,186,195,opel
492,85,43,66,130,57,6,151,45,19,143,173,333,168,86,4,9,180,183,bus
709,95,42,96,197,65,9,178,37,21,141,199,474,149,67,1,29,193,200,opel
143,80,43,68,120,54,8,150,45,19,145,171,329,176,85,4,8,179,183,bus
530,88,48,90,178,60,8,175,38,21,152,200,460,198,68,13,16,192,199,saab

In [11]:
from sklearn.preprocessing import LabelEncoder

X , y = df.drop('Class',axis=1) , df['Class']
encoder = LabelEncoder()
y_en = encoder.fit_transform(y)

kfold = StratifiedKFold(n_splits=5 , shuffle=True , random_state=26)
gbm = GradientBoostingClassifier(random_state=26)

### Accuracy Score

In [12]:
results = cross_val_score(gbm,X,y_en,cv=kfold)  # default scoring='accuracy_score'
results

array([0.77058824, 0.76923077, 0.78698225, 0.78106509, 0.75147929])

### Log Loss

In [13]:
results = cross_val_score(gbm,X,y_en,cv=kfold,scoring='neg_log_loss')  
results

array([-0.46420906, -0.47148921, -0.43516682, -0.47498426, -0.55013841])

# Exercise

In [16]:
import numpy as np
from tqdm import tqdm
from sklearn.linear_model import LogisticRegression

solvers = ['lbfgs', 'saga', 'sag', 'newton-cg', 'newton-cholesky']
scores = []

for s  in tqdm(solvers):
    lr = LogisticRegression(solver=s)
    kfold = StratifiedKFold(n_splits=5 , shuffle=True , random_state=26)
    results = cross_val_score(lr,X,y_en,cv=kfold,scoring='neg_log_loss')
    scores.append([s,np.mean(results)])
df_scores = pd.DataFrame(scores,columns=['Solver','Fold Log Loss'])
df_scores.sort_values('Fold Log Loss',ascending=False,ignore_index=True)

100%|██████████| 5/5 [00:05<00:00,  1.11s/it]

            Solver  Fold Log Loss
0        newton-cg      -0.416957
1  newton-cholesky      -0.438304
2            lbfgs      -0.679773
3              sag      -0.764025
4             saga      -0.848120

In [20]:
import numpy as np
from tqdm import tqdm
from sklearn.linear_model import LogisticRegression

solvers = ['lbfgs', 'saga', 'sag', 'newton-cg', 'newton-cholesky']
Cs = np.linspace(0.01,3,5)
scores = []

for s  in tqdm(solvers):
    for c in Cs:
        lr = LogisticRegression(solver=s,C=c)
        kfold = StratifiedKFold(n_splits=5 , shuffle=True , random_state=26)
        results = cross_val_score(lr,X,y_en,cv=kfold,scoring='neg_log_loss')
        scores.append([s,c,np.mean(results)])
df_scores = pd.DataFrame(scores,columns=['Solver','C','Fold Log Loss'])
df_scores.sort_values('Fold Log Loss',ascending=False,ignore_index=True)

100%|██████████| 5/5 [00:25<00:00,  5.10s/it]

             Solver       C  Fold Log Loss
0         newton-cg  0.7575      -0.414607
1         newton-cg  1.5050      -0.421581
2         newton-cg  2.2525      -0.427825
3         newton-cg  3.0000      -0.431223
4   newton-cholesky  0.7575      -0.432451
5   newton-cholesky  1.5050      -0.447914
6   newton-cholesky  2.2525      -0.458194
7   newton-cholesky  3.0000      -0.465749
8   newton-cholesky  0.0100      -0.470541
9         newton-cg  0.0100      -0.472532
10            lbfgs  0.7575      -0.670045
11            lbfgs  2.2525      -0.676708
12            lbfgs  3.0000      -0.679349
13            lbfgs  1.5050      -0.680220
14            lbfgs  0.0100      -0.695260
15              sag  1.5050      -0.764053
16              sag  0.7575      -0.764065
17              sag  2.2525      -0.764206
18              sag  3.0000      -0.764267
19              sag  0.0100      -0.766278
20             saga  3.0000      -0.847952
21             saga  2.2525      -0.848057
22             saga  0.7575      -0.848077
23             saga  1.5050      -0.848141
24             saga  0.0100      -0.849270