# ----- Voting Ensembling Technique -----

In [67]:
import warnings 
warnings.filterwarnings('ignore')

In [68]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from tqdm import tqdm

from sklearn.ensemble import VotingClassifier

In [78]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Wisconsin\BreastCancer.csv",index_col=0)
df.sample(5)

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
1276091,1,3,1,1,2,1,2,2,1,Benign
1311108,1,1,1,3,2,1,1,1,1,Benign
1054590,7,3,2,10,5,10,5,4,4,Malignant
1201936,5,10,10,3,8,1,5,10,3,Malignant
1216694,10,8,8,4,10,10,8,1,1,Malignant

In [86]:
X , y = df.drop('Class',axis=1) , df['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [87]:
tree = DecisionTreeClassifier(random_state=26)
lr = LogisticRegression()
knn = KNeighborsClassifier()

voting = VotingClassifier([('TREE',tree),('LR',lr),('KNN',knn)])
voting.fit(X_train,y_train)

VotingClassifier(estimators=[('TREE', DecisionTreeClassifier(random_state=26)),
                             ('LR', LogisticRegression()),
                             ('KNN', KNeighborsClassifier())])

In [88]:
y_pred = voting.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572

In [89]:
voting.named_estimators_

{'TREE': DecisionTreeClassifier(random_state=26),
 'LR': LogisticRegression(),
 'KNN': KNeighborsClassifier()}

In [90]:
voting.named_estimators_['TREE']

DecisionTreeClassifier(random_state=26)

### Performnace Of Individual Estimators

In [91]:
import numpy as np
y_test_enc = np.where(y_test == "Malignant",1,0)
y_pred = voting.named_estimators_['TREE'].predict(X_test)
print('Tree Accuracy ->',accuracy_score(y_test_enc,y_pred))
y_pred = voting.named_estimators_['LR'].predict(X_test)
print('LR Accuracy ->',accuracy_score(y_test_enc,y_pred))
y_pred = voting.named_estimators_['KNN'].predict(X_test)
print('KNN Accuracy ->',accuracy_score(y_test_enc,y_pred))

Tree Accuracy -> 0.9476190476190476
LR Accuracy -> 0.9619047619047619
KNN Accuracy -> 0.9619047619047619

In [92]:
scores = []
for d in tqdm([None,2,3,4,5]):
    for s in ['lbfgs','saga','sag','liblinear']:
        for k in [2,5,10]:           
            tree = DecisionTreeClassifier(random_state=26,max_depth=d)
            lr = LogisticRegression(solver=s)
            knn = KNeighborsClassifier(n_neighbors=k)
            voting = VotingClassifier([('TREE',tree),('LR',lr),('KNN',knn)],voting='soft')  
            # voting = soft -> Predicted class probabilities , and avg them
            # default : Voting = hard -> predict class label , and majority is choosen
            voting.fit(X_train,y_train)
            y_pred = voting.predict(X_test)
            scores.append([d,s,k,accuracy_score(y_test,y_pred)])

100%|██████████| 5/5 [00:01<00:00,  3.09it/s]

In [93]:
df_scores = pd.DataFrame(scores,columns=['Depth','Solver','Neighbors','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

    Depth     Solver  Neighbors  Accuracy
27    3.0       saga          2  0.971429
24    3.0      lbfgs          2  0.971429
33    3.0  liblinear          2  0.971429
30    3.0        sag          2  0.971429
36    4.0      lbfgs          2  0.971429
39    4.0       saga          2  0.971429
45    4.0  liblinear          2  0.971429
42    4.0        sag          2  0.971429
21    2.0  liblinear          2  0.966667
18    2.0        sag          2  0.966667
15    2.0       saga          2  0.966667
12    2.0      lbfgs          2  0.966667
19    2.0        sag          5  0.961905
17    2.0       saga         10  0.961905
16    2.0       saga          5  0.961905
20    2.0        sag         10  0.961905
8     NaN        sag         10  0.961905
9     NaN  liblinear          2  0.961905
14    2.0      lbfgs         10  0.961905
13    2.0      lbfgs          5  0.961905
23    2.0  liblinear         10  0.961905
22    2.0  liblinear          5  0.961905
11    NaN  liblinear         10  0.961905
6     NaN        sag          2  0.961905
0     NaN      lbfgs          2  0.961905
2     NaN      lbfgs         10  0.961905
3     NaN       saga          2  0.961905
5     NaN       saga         10  0.961905
59    5.0  liblinear         10  0.961905
44    4.0        sag         10  0.961905
46    4.0  liblinear          5  0.961905
47    4.0  liblinear         10  0.961905
26    3.0      lbfgs         10  0.961905
25    3.0      lbfgs          5  0.961905
29    3.0       saga         10  0.961905
31    3.0        sag          5  0.961905
35    3.0  liblinear         10  0.961905
34    3.0  liblinear          5  0.961905
32    3.0        sag         10  0.961905
38    4.0      lbfgs         10  0.961905
41    4.0       saga         10  0.961905
40    4.0       saga          5  0.961905
43    4.0        sag          5  0.961905
28    3.0       saga          5  0.961905
57    5.0  liblinear          2  0.961905
54    5.0        sag          2  0.961905
56    5.0        sag         10  0.961905
53    5.0       saga         10  0.961905
48    5.0      lbfgs          2  0.961905
50    5.0      lbfgs         10  0.961905
51    5.0       saga          2  0.961905
10    NaN  liblinear          5  0.957143
1     NaN      lbfgs          5  0.957143
4     NaN       saga          5  0.957143
7     NaN        sag          5  0.957143
37    4.0      lbfgs          5  0.957143
49    5.0      lbfgs          5  0.957143
52    5.0       saga          5  0.957143
55    5.0        sag          5  0.957143
58    5.0  liblinear          5  0.957143

# Exercise

In [94]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Concrete_Strength\Concrete_Data.csv")
df.sample(5)

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
270,231.8,0.0,121.6,174.0,6.7,1056.4,778.5,14,26.77
302,290.4,0.0,96.2,168.1,9.4,961.2,865.0,56,45.08
720,203.5,305.3,0.0,203.5,0.0,963.4,630.0,90,51.86
576,339.2,0.0,0.0,185.7,0.0,1069.2,754.3,7,21.18
466,190.3,0.0,125.2,166.6,9.9,1079.0,798.9,100,33.56

In [95]:
X , y = df.drop('Strength',axis=1) , df['Strength']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [106]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.metrics import r2_score

In [198]:
lr = LinearRegression()
rd = Ridge()
ls = Lasso()
dtr = DecisionTreeRegressor(random_state=26)

In [202]:
voting = VotingRegressor([('LR',lr),('RD',rd),('LS',ls),('TREE',dtr)])
voting.fit(X_train,y_train)

VotingRegressor(estimators=[('LR', LinearRegression()), ('RD', Ridge()),
                            ('LS', Lasso()),
                            ('TREE', DecisionTreeRegressor(random_state=26))])

In [203]:
y_pred = voting.predict(X_test)
r2_score(y_test,y_pred)

0.7557599363240081

In [204]:
# Estimate Individual Estimator
y_pred = voting.named_estimators_['LR'].predict(X_test)
print('R2 Score For Linear ->',r2_score(y_test,y_pred))
y_pred = voting.named_estimators_['RD'].predict(X_test)
print('R2 Score For Ridge ->',r2_score(y_test,y_pred))
y_pred = voting.named_estimators_['LS'].predict(X_test)
print('R2 Score For Lasso ->',r2_score(y_test,y_pred))
y_pred = voting.named_estimators_['TREE'].predict(X_test)
print('R2 Score For Tree ->',r2_score(y_test,y_pred))

R2 Score For Linear -> 0.6181464728464399
R2 Score For Ridge -> 0.6181470326108837
R2 Score For Lasso -> 0.6188405404462809
R2 Score For Tree -> 0.8500256114787615

### Apply Weights

In [207]:
voting = VotingRegressor([('LR',lr),('RD',rd),('LS',ls),('TREE',dtr)],
                        weights=[0.9,0.9,1,10])
voting.fit(X_train,y_train)

VotingRegressor(estimators=[('LR', LinearRegression()), ('RD', Ridge()),
                            ('LS', Lasso()),
                            ('TREE', DecisionTreeRegressor(random_state=26))],
                weights=[0.9, 0.9, 1, 10])

In [208]:
y_pred = voting.predict(X_test)
r2_score(y_test,y_pred)

0.8717692447087042

# ----- Bootstrap Sampling Estimation Technique -----

In [209]:
from sklearn.ensemble import BaggingClassifier

In [210]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Wisconsin\BreastCancer.csv",index_col=0)
df.sample(5)

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
474162,8,7,8,5,5,10,9,10,1,Malignant
1306282,6,6,7,10,3,10,8,10,2,Malignant
1260659,3,1,4,1,2,1,1,1,1,Benign
1226012,4,1,1,3,1,5,2,1,1,Malignant
1350319,5,7,4,1,6,1,7,10,3,Malignant

In [211]:
X , y = df.drop('Class',axis=1) , df['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [212]:
lr = LogisticRegression()
bagg = BaggingClassifier(estimator=lr,n_estimators=15,random_state=26)
bagg.fit(X_train,y_train)

BaggingClassifier(estimator=LogisticRegression(), n_estimators=15,
                  random_state=26)

In [213]:
y_pred = bagg.predict(X_test)
accuracy_score(y_pred,y_test)

0.9571428571428572

In [214]:
lr = LogisticRegression()
knn = KNeighborsClassifier()
dtc = DecisionTreeClassifier(random_state=26)

In [215]:
est = [lr,knn,dtc]
n_samples = [10,25,50]
scores = []
for e in est :
    for n in n_samples:
        bagg = BaggingClassifier(estimator=e,n_estimators=n,random_state=26)
        bagg.fit(X_train,y_train)
        y_pred = bagg.predict(X_test)
        scores.append([e,n,accuracy_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['Estimator','N','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

                                 Estimator   N  Accuracy
6  DecisionTreeClassifier(random_state=26)  10  0.966667
5                   KNeighborsClassifier()  50  0.966667
7  DecisionTreeClassifier(random_state=26)  25  0.966667
3                   KNeighborsClassifier()  10  0.961905
2                     LogisticRegression()  50  0.961905
8  DecisionTreeClassifier(random_state=26)  50  0.961905
4                   KNeighborsClassifier()  25  0.961905
1                     LogisticRegression()  25  0.957143
0                     LogisticRegression()  10  0.952381

# Exercise on concrete.csv -> algo LR,RD,LS,TREE
Regression

In [216]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Concrete_Strength\Concrete_Data.csv")
df.sample(5)

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.29
228,168.0,42.1,163.8,121.8,5.7,1058.7,780.1,100,39.23
661,141.3,212.0,0.0,203.5,0.0,971.8,748.5,7,10.39
1009,298.1,0.0,107.0,186.4,6.1,879.0,815.2,28,42.64
505,491.0,26.0,123.0,201.0,3.9,822.0,699.0,7,37.92

In [217]:
X , y = df.drop('Strength',axis=1) , df['Strength']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [218]:
from sklearn.ensemble import BaggingRegressor

In [225]:
lr = LinearRegression()
est = [lr,rd,ls,dtr]
n_samples = [10,25,50]
scores = []
for e in tqdm(est) :
    for n in n_samples:
        bagg = BaggingRegressor(estimator=e,n_estimators=n,random_state=26)
        bagg.fit(X_train,y_train)
        y_pred = bagg.predict(X_test)
        scores.append([e,n,r2_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['Estimator','N','R2 Score'])
df_scores.sort_values('R2 Score',ascending=False)

100%|██████████| 4/4 [00:01<00:00,  3.34it/s]

                                 Estimator   N  R2 Score
11  DecisionTreeRegressor(random_state=26)  50  0.896730
10  DecisionTreeRegressor(random_state=26)  25  0.893895
9   DecisionTreeRegressor(random_state=26)  10  0.893069
6                                  Lasso()  10  0.620327
3                                  Ridge()  10  0.619630
0                       LinearRegression()  10  0.619629
8                                  Lasso()  50  0.618218
5                                  Ridge()  50  0.617487
2                       LinearRegression()  50  0.617486
7                                  Lasso()  25  0.616078
4                                  Ridge()  25  0.615382
1                       LinearRegression()  25  0.615382