In [12]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector , make_column_transformer

from sklearn.multiclass import OneVsOneClassifier
from tqdm import tqdm

In [13]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Vehicle Silhouettes\Vehicle.csv")
df.sample(5)

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
624,84,36,75,136,55,6,140,48,18,125,166,290,138,71,4,36,189,195,saab
657,89,45,85,149,59,11,158,43,20,158,177,362,173,75,12,16,183,193,van
421,98,48,101,195,61,11,207,31,23,152,227,650,193,71,5,7,189,196,opel
462,97,47,81,183,64,8,168,39,20,150,193,426,182,70,11,2,192,198,opel
136,86,48,75,136,58,10,161,43,20,163,170,371,185,75,3,1,183,192,van

In [14]:
X , y = df.drop('Class',axis=1), df['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

### Kernel = linear

In [17]:
cs = np.linspace(0.001,10,20)
scores = []
dfs = ['ovo','ovr']
scaler = StandardScaler()

for c in tqdm(cs) :
    for f in dfs:
        svm = SVC(kernel='linear',C=c,decision_function_shape=f)
        pipe = Pipeline([('SCL',scaler),('SVM',svm)])
        pipe.fit(X_train,y_train)
        y_pred = pipe.predict(X_test)
        scores.append([c,f,accuracy_score(y_test,y_pred)])
df_score = pd.DataFrame(scores,columns=['C','Decision','Accuracy'])
df_score.sort_values('Accuracy',ascending=False)

100%|██████████| 20/20 [00:01<00:00, 12.73it/s]

            C Decision  Accuracy
11   2.632316      ovr  0.807087
10   2.632316      ovo  0.807087
14   3.684842      ovo  0.807087
15   3.684842      ovr  0.807087
9    2.106053      ovr  0.807087
8    2.106053      ovo  0.807087
6    1.579789      ovo  0.803150
7    1.579789      ovr  0.803150
24   6.316158      ovo  0.803150
25   6.316158      ovr  0.803150
18   4.737368      ovo  0.803150
19   4.737368      ovr  0.803150
20   5.263632      ovo  0.803150
21   5.263632      ovr  0.803150
13   3.158579      ovr  0.803150
12   3.158579      ovo  0.803150
16   4.211105      ovo  0.803150
17   4.211105      ovr  0.803150
22   5.789895      ovo  0.803150
23   5.789895      ovr  0.803150
26   6.842421      ovo  0.799213
27   6.842421      ovr  0.799213
28   7.368684      ovo  0.795276
29   7.368684      ovr  0.795276
32   8.421211      ovo  0.791339
33   8.421211      ovr  0.791339
34   8.947474      ovo  0.791339
35   8.947474      ovr  0.791339
36   9.473737      ovo  0.791339
37   9.473737      ovr  0.791339
30   7.894947      ovo  0.791339
31   7.894947      ovr  0.791339
38  10.000000      ovo  0.791339
39  10.000000      ovr  0.791339
5    1.053526      ovr  0.787402
4    1.053526      ovo  0.787402
3    0.527263      ovr  0.779528
2    0.527263      ovo  0.779528
1    0.001000      ovr  0.425197
0    0.001000      ovo  0.425197

### Kernel = rbf(Radial Basis Funation)

In [22]:
cs = np.linspace(0.001,10,20)
gs = np.linspace(0.1,10,20)
scores = []
dfs = ['ovo','ovr']
scaler = StandardScaler()

for c in tqdm(cs) :
    for g in gs:
        for f in dfs:
            svm = SVC(kernel='rbf',C=c,decision_function_shape=f,gamma=g)
            pipe = Pipeline([('SCL',scaler),('SVM',svm)])
            pipe.fit(X_train,y_train)
            y_pred = pipe.predict(X_test)
            scores.append([c,g,f,accuracy_score(y_test,y_pred)])
df_score = pd.DataFrame(scores,columns=['C','Gamma','Decision','Accuracy'])
df_score.sort_values('Accuracy',ascending=False)

100%|██████████| 20/20 [00:44<00:00,  2.21s/it]

            C     Gamma Decision  Accuracy
360  4.737368  0.100000      ovo  0.803150
361  4.737368  0.100000      ovr  0.803150
401  5.263632  0.100000      ovr  0.799213
400  5.263632  0.100000      ovo  0.799213
280  3.684842  0.100000      ovo  0.799213
..        ...       ...      ...       ...
4    0.001000  1.142105      ovo  0.255906
3    0.001000  0.621053      ovr  0.255906
2    0.001000  0.621053      ovo  0.255906
1    0.001000  0.100000      ovr  0.255906
0    0.001000  0.100000      ovo  0.255906

[800 rows x 4 columns]