In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error

In [2]:
df = pd.read_csv(r"C:\Users\PATEL VIRAJ\OneDrive\Desktop\PGCP_AI\Machine_Learning\Datasets\pizza.csv")

X = df[['Promote']]
y = df['Sales']

poly = PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
X_poly

    Promote  Promote^2  Promote^3
0      23.0      529.0    12167.0
1      56.0     3136.0   175616.0
2      34.0     1156.0    39304.0
3      25.0      625.0    15625.0
4      67.0     4489.0   300763.0
5      82.0     6724.0   551368.0
6      46.0     2116.0    97336.0
7      14.0      196.0     2744.0
8       6.0       36.0      216.0
9      47.0     2209.0   103823.0
10     52.0     2704.0   140608.0
11     88.0     7744.0   681472.0
12     71.0     5041.0   357911.0
13     78.0     6084.0   474552.0
14     66.0     4356.0   287496.0
15     44.0     1936.0    85184.0
16     68.0     4624.0   314432.0
17     90.0     8100.0   729000.0
18     22.0      484.0    10648.0

In [3]:
X_train,X_test,y_train,y_test = train_test_split(X_poly,y,random_state=26,train_size=0.7)
model = LinearRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
root_mean_squared_error(y_test,y_pred)

np.float64(60.15805716377442)

In [4]:
print(model.coef_)
print(model.intercept_)

[ 1.01182091e+01  3.00266123e-01 -1.98257181e-03]
165.1168845980036

# Excercise 
for bostone apply degree 2,3,4,5 apply regression and compare rmse

In [5]:
import pandas as pd 
import matplotlib.pyplot as plt

In [6]:
df  = pd.read_csv(r'C:\Users\PATEL VIRAJ\OneDrive\Desktop\PGCP_AI\Machine_Learning\Datasets\Boston.csv')
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [7]:
X = df.drop('medv',axis=1)
y = df['medv']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=26)

In [9]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [10]:
from sklearn.metrics import root_mean_squared_error,r2_score
y_pred = model.predict(X_test)
print('R2 Score ->',r2_score(y_test,y_pred))
print('RMSE ->',root_mean_squared_error(y_test,y_pred))

R2 Score -> 0.7147484921083873
RMSE -> 4.642869284426379

In [11]:
# Polynomial Regression
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree = 3,include_bias = False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X_poly,y,train_size=0.8,random_state=26)

In [13]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred = model.predict(X_test)
print('R2 Score ->',r2_score(y_test,y_pred))
print('RMSE ->',root_mean_squared_error(y_test,y_pred))

R2 Score -> -21464.56180054885
RMSE -> 1273.630972935639

In [15]:
#  for degree 2,3,4,5
degrees = [2,3,4,5]
score = []

In [16]:
for x in degrees:
    df  = pd.read_csv(r'C:\Users\PATEL VIRAJ\OneDrive\Desktop\PGCP_AI\Machine_Learning\Datasets\Boston.csv')
    X = df.drop('medv',axis=1)
    y = df['medv']
    poly = PolynomialFeatures(degree = x,include_bias = False).set_output(transform='pandas')
    X_poly = poly.fit_transform(X)
    X_train,X_test,y_train,y_test = train_test_split(X_poly,y,train_size=0.8,random_state=26)
    model = LinearRegression()
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    score.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])

In [20]:
scores = pd.DataFrame(score,columns=['Degree','R2 Score','Score'])
scores

   Degree      R2 Score        Score
0       2      0.772455     4.146730
1       3 -21464.561801  1273.630973
2       4   -927.586210   264.901000
3       5    -89.082398    82.507314

In [21]:
scores.sort_values('Score')

   Degree      R2 Score        Score
0       2      0.772455     4.146730
3       5    -89.082398    82.507314
2       4   -927.586210   264.901000
1       3 -21464.561801  1273.630973