In [42]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score

In [43]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\housing.csv")
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [44]:
X = df.drop('price',axis=1)
y = df['price']

In [45]:
encoder = OneHotEncoder(sparse_output = False,drop='first').set_output(transform='pandas')
numeric = X.select_dtypes(include='number')
category = X.select_dtypes(include=['object','str'])
X_encoded = encoder.fit_transform(category)
X_encoded = pd.concat([numeric,X_encoded],axis=1)
X_encoded.head()

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,5850,3,1,2,1,1.0,0.0,1.0,0.0,0.0,0.0
1,4000,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
2,3060,3,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
3,6650,3,1,2,0,1.0,1.0,0.0,0.0,0.0,0.0
4,6360,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X_encoded,y,train_size=0.7,random_state=26)

In [47]:
model = Ridge() # default alpha = 1
model.fit(X_train,y_train)
model.coef_

array([4.56610469e+00, 2.06191429e+03, 1.33910373e+04, 6.02801491e+03,
       3.34603053e+03, 6.28094679e+03, 3.21975767e+03, 6.71200452e+03,
       1.04578147e+04, 1.23047338e+04, 9.41029097e+03])

In [48]:
y_pred = model.predict(X_test)
print('R2 Score ->',r2_score(y_test,y_pred))
print('RMSE ->',root_mean_squared_error(y_test,y_pred))

R2 Score -> 0.6784289744793978
RMSE -> 15070.47480878495

In [49]:
# Try For alpha = [0.1,0.25,0.7,1,1.5,2,5,10,50]
alpha = [0.1,0.25,0.7,1,1.5,2,5,10,50]
score =[]

In [50]:
for x in alpha:
    model = Ridge(alpha=x) 
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print('R2 Score ->',r2_score(y_test,y_pred))
    print('RMSE ->',root_mean_squared_error(y_test,y_pred))
    score.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])

R2 Score -> 0.6791065537995606
RMSE -> 15054.589007441034
R2 Score -> 0.6789976120224888
RMSE -> 15057.144270758692
R2 Score -> 0.6786608730449469
RMSE -> 15065.03984806656
R2 Score -> 0.6784289744793978
RMSE -> 15070.47480878495
R2 Score -> 0.6780311442617772
RMSE -> 15079.794114038725
R2 Score -> 0.6776211496077685
RMSE -> 15089.39235292554
R2 Score -> 0.6749937971261597
RMSE -> 15150.756031047045
R2 Score -> 0.6703287867774149
RMSE -> 15259.10260185512
R2 Score -> 0.632982345203871
RMSE -> 16100.225467703773

In [51]:
scores

   Alpha  R2 Score          RMSE
0   0.10  0.676365  15292.333359
1   0.25  0.676179  15296.719828
2   0.70  0.675628  15309.735851
3   1.00  0.675265  15318.297579
4   1.50  0.674668  15332.370906
5   2.00  0.674081  15346.210680
6   5.00  0.670724  15425.027402
7  10.00  0.665600  15544.592971
8  50.00  0.631352  16321.195590

In [55]:
scores.sort_values('RMSE')

ValueError: The column label 'RMSE' is not unique.
For a multi-index, the label must be a tuple with elements corresponding to each level.