In [6]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from sentence_transformers import SentenceTransformer

In [7]:
df = pd.read_csv('/content/titles.csv')
df.sample(5)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
4509,tm461532,Kill Me If You Dare,MOVIE,Kill Me Darling is the story of a couple who d...,2019,NaN,104,"['romance', 'comedy']",['TR'],NaN,tt9749604,4.4,1764.0,3.102,4.2
579,tm308960,Gina Yashere: Skinny B*tch,MOVIE,Gina Yashere's performance on American TV's La...,2008,NaN,57,"['comedy', 'documentation']",['GB'],NaN,tt1722436,6.5,86.0,0.955,6.5
4065,tm426630,Soni,MOVIE,"Soni, a young policewoman in Delhi, and her su...",2019,NaN,97,"['crime', 'drama']",['IN'],NaN,tt6078866,7.1,2788.0,2.862,6.9
2652,tm361505,48 Christmas Wishes,MOVIE,Holiday magic has never gleamed brighter as Sa...,2017,NaN,84,"['family', 'comedy', 'fantasy']",['CA'],NaN,tt7422638,3.9,1105.0,8.282,5.4
609,ts23353,Together,SHOW,Together is a Singaporean Chinese drama produc...,2009,TV-14,45,"['drama', 'comedy']",['SG'],1.0,NaN,NaN,NaN,0.628,NaN

In [8]:
df.shape

(5850, 15)

In [9]:
ind_movie = df[(df['production_countries'].str.contains('IN')) & (df['type'] == 'MOVIE')]
ind_movie.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
19,tm94651,Dostana,MOVIE,Two close friends decide to enter law enforcem...,1980,NaN,161,"['drama', 'comedy', 'crime', 'romance', 'action']",['IN'],NaN,tt0080653,2.1,25.0,3.980,4.9
21,tm100027,Alibaba Aur 40 Chor,MOVIE,The movie is based on the story of Ali Baba an...,1979,NaN,146,"['drama', 'romance', 'action', 'fantasy', 'fam...","['SU', 'IN']",NaN,tt0079749,6.2,565.0,2.582,6.8
25,tm356209,Singapore,MOVIE,"When his employee disappears in Singapore, Shy...",1960,NaN,158,"['drama', 'thriller', 'crime']",['IN'],NaN,tt0268639,6.4,84.0,0.792,6.3
29,tm336403,Khoon Khoon,MOVIE,As a crazed killer blazes a trail of blood thr...,1973,NaN,131,"['crime', 'thriller']",['IN'],NaN,tt0230412,5.1,41.0,1.948,3.8
30,tm107372,Manoranjan,MOVIE,Havaldar Ratan is a rookie at the local police...,1974,NaN,162,"['romance', 'drama', 'comedy']",['IN'],NaN,tt0071811,6.5,237.0,1.532,5.3

In [10]:
ind_movie.shape

(577, 15)

In [11]:
us_movie = df[(df['production_countries'].str.contains('US')) & (df['type'] == 'MOVIE')]
us_movie.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600
7,tm14873,Dirty Harry,MOVIE,When a madman dubbed 'Scorpio' terrorizes San ...,1971,R,102,"['thriller', 'action', 'crime']",['US'],NaN,tt0066999,7.7,155051.0,12.817,7.500
8,tm119281,Bonnie and Clyde,MOVIE,"In the 1930s, bored waitress Bonnie Parker fal...",1967,R,110,"['crime', 'drama', 'action']",['US'],NaN,tt0061418,7.7,112048.0,15.687,7.500

In [12]:
us_movie.shape

(1499, 15)

In [13]:
model = SentenceTransformer('BAAI/bge-small-en-v1.5')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  133MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [14]:
all_desc = list(ind_movie['description'])
out_embs = []
for r in tqdm(all_desc):
  embd = model.encode(r)
  out_embs.append(embd)
out_embs = np.array(out_embs)

100%|██████████| 577/577 [00:08<00:00, 70.53it/s]

In [15]:
out_embs.shape

(577, 384)

In [16]:
ind_movie['MovieID'] = ind_movie['id']+'-'+ind_movie['title']
df_embd = pd.DataFrame(out_embs, index=list(ind_movie['MovieID']))
df_embd

/tmp/ipykernel_818/3792298518.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind_movie['MovieID'] = ind_movie['id']+'-'+ind_movie['title']

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
tm94651-Dostana,-0.075357,0.013868,-0.061348,-0.009090,-0.004694,0.005166,0.089489,-0.046013,0.048869,-0.018892,...,0.022732,-0.026808,0.006294,0.038266,-0.005323,-0.062236,0.033453,0.020772,0.049413,0.022834
tm100027-Alibaba Aur 40 Chor,-0.044140,0.060243,-0.041446,-0.058401,-0.030420,0.064920,0.065799,-0.036992,0.012539,-0.077255,...,0.031550,-0.054891,0.015133,-0.024666,-0.019042,-0.131373,0.014510,0.012415,-0.009698,0.019127
tm356209-Singapore,0.033862,0.030536,-0.017178,-0.036037,0.088664,-0.030930,0.148762,0.001592,0.019263,-0.022572,...,0.023382,-0.013798,-0.014579,0.031582,-0.072774,0.019934,0.000184,0.010525,-0.041923,-0.008498
tm336403-Khoon Khoon,-0.149428,0.020323,0.018530,0.007980,0.055575,0.028446,0.104850,-0.024781,-0.041700,-0.006586,...,0.063270,-0.055972,-0.006201,0.087120,0.032169,-0.029733,0.059928,0.019334,0.041777,-0.091707
tm107372-Manoranjan,-0.044192,0.066234,-0.047135,-0.032663,0.065942,-0.011514,0.099225,-0.020301,-0.015988,0.024434,...,-0.018728,-0.052115,-0.010343,-0.006524,-0.032688,-0.040701,0.013472,0.105296,0.001144,-0.000315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tm1004011-Time to Dance,-0.060569,-0.043502,0.023263,0.021714,0.025721,0.021548,0.039579,-0.021274,0.048758,-0.043658,...,-0.026304,-0.009670,0.006067,-0.007580,-0.002505,0.013864,-0.065078,-0.048671,0.012461,-0.044530
tm987730-Tribhanga,-0.035807,0.042290,-0.048692,0.040487,-0.019386,0.014480,0.062826,0.014035,0.019472,-0.008724,...,0.019570,-0.012333,0.069821,0.022993,-0.055982,-0.011172,0.061018,0.067908,-0.031457,-0.000590
tm988613-Madam Chief Minister,-0.040465,0.064742,0.002758,0.005937,0.017782,0.054613,0.013698,-0.013054,-0.054693,-0.012611,...,0.019959,-0.047766,0.019578,-0.034212,-0.022108,-0.017424,-0.037743,0.029874,-0.017669,-0.006640
tm1110241-Kaaval,-0.034413,0.052420,-0.049851,-0.011543,0.007684,-0.050671,0.056916,-0.026559,-0.032186,-0.056518,...,-0.003989,-0.059536,-0.020717,0.037187,-0.020789,-0.057904,0.068252,0.021265,-0.036518,-0.015049
tm996479-Tuesdays And Fridays,0.017332,0.064089,-0.040096,-0.036038,-0.040482,-0.041584,-0.027363,-0.023101,-0.003244,-0.073449,...,-0.069667,-0.034122,-0.024787,0.040781,0.033388,-0.018029,0.037538,-0.031015,0.005410,0.013119

In [17]:
from sklearn.cluster import HDBSCAN
from sklearn.metrics import silhouette_score

In [18]:
hdbscan = HDBSCAN(min_cluster_size=2)
hdbscan.fit(out_embs)

HDBSCAN(min_cluster_size=2)

In [19]:
df_embd['hdbscan_cluster'] = hdbscan.labels_
df_embd['hdbscan_cluster'].value_counts()

hdbscan_cluster
-1     413
 57     20
 40      9
 58      6
 48      5
 25      4
 36      4
 27      4
 51      3
 50      3
 15      3
 18      3
 38      3
 52      3
 21      3
 2       3
 11      2
 42      2
 35      2
 14      2
 19      2
 13      2
 43      2
 39      2
 47      2
 12      2
 29      2
 41      2
 54      2
 32      2
 34      2
 53      2
 6       2
 10      2
 20      2
 55      2
 1       2
 17      2
 46      2
 7       2
 22      2
 3       2
 49      2
 56      2
 45      2
 37      2
 28      2
 31      2
 5       2
 23      2
 4       2
 30      2
 8       2
 33      2
 26      2
 0       2
 16      2
 44      2
 9       2
 24      2
Name: count, dtype: int64

In [20]:
ind_movie[(df_embd['hdbscan_cluster'] == 48).values][['title','description']]

,title,description
434,Dil Chahta Hai,Three inseparable childhood friends are just o...
566,Main Aurr Mrs Khanna,"Three people, each having different aspiration..."
721,Zindagi Na Milegi Dobara,Three friends who were inseparable in childhoo...
1455,Pyaar Ka Punchnama 2,"After falling in love, three roommates experie..."
4248,Love,The story of a family and the various situatio...

In [21]:
# For US movies

In [22]:
us_movie.isnull().sum()

id                         0
title                      0
type                       0
description                3
release_year               0
age_certification        681
runtime                    0
genres                     0
production_countries       0
seasons                 1499
imdb_id                  109
imdb_score               125
imdb_votes               134
tmdb_popularity            4
tmdb_score                20
dtype: int64

In [23]:
all_desc = list(us_movie['description'])
out_embs = []
for r in tqdm(all_desc):
  embd = model.encode(r)
  out_embs.append(embd)
out_embs = np.array(out_embs)

 85%|████████▍ | 1271/1499 [00:16<00:03, 75.60it/s]

ValueError: Unsupported input type: float. Expected one of: str, dict, PIL.Image.Image, np.ndarray, torch.Tensor

# **Exercise**

In [24]:
df = pd.read_csv('/content/historic_articles.csv')
df.head()

,source,category,link,author,published_at,header,subheader,content
0,firstpost,india,https://www.firstpost.com/india/supreme-court-...,FP Staff,"September 21, 2020 20:11:56 IST","Supreme Court, in anti-CAA blockade case, says...",While listening to a batch of petitions agains...,The Supreme Court on Monday said there cannot ...
1,firstpost,india,https://www.firstpost.com/india/rti-reponse-re...,Sumit Chaturvedi,"September 20, 2020 10:02:10 IST",RTI reponse reveals over 18 lakh ration cards ...,The large backlog of pending ration card appli...,Lakhs of migrant workers who returned to their...
2,firstpost,india,https://www.firstpost.com/india/pilot-dies-as-...,Press Trust of India,"September 21, 2020 15:32:17 IST",Pilot dies as four-seater training aircraft cr...,"The aircraft, which belonged to the Indira Gan...",Azamgarh: A four-seater training aircraft cras...
3,firstpost,india,https://www.firstpost.com/india/hcl-technologi...,Press Trust of India,"September 21, 2020 14:15:16 IST",HCL Technologies to acquire Australia’s DWS Lt...,"DWS, with FY20 revenue at AUS $167.9 million, ...",New Delhi: HCL Technologies on Monday said it ...
4,firstpost,india,https://www.firstpost.com/india/parliament-mon...,FP Staff,"September 22, 2020 10:42:06 IST",Parliament LIVE Updates: Pralhad Joshi says go...,Parliament LIVE Updates: Parliamentary Affair ...,Parliament LATEST Updates: Parliamentary Affai...

In [25]:
df.isna().sum()
df.dropna(inplace=True)

In [26]:
all_content = list(df['content'])
embd = []
for c in tqdm(all_content):
  em = model.encode(c)
  embd.append(em)
embd = np.array(embd)

100%|██████████| 1553/1553 [00:25<00:00, 61.13it/s]

In [27]:
df_embd = pd.DataFrame(embd)
df_embd

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.080176,0.023172,-0.065073,-0.003892,-0.039935,0.057297,0.049721,-0.043395,-0.016816,0.063032,...,-0.012366,0.007640,-0.046591,0.004088,-0.037538,0.053441,0.072454,-0.012145,-0.027155,0.045201
1,-0.042456,-0.023293,-0.039460,-0.002688,0.002964,0.000729,0.002834,-0.034946,-0.002039,-0.013722,...,0.028367,-0.083962,-0.000761,-0.033618,0.017383,0.003009,-0.014859,-0.005724,-0.004869,-0.021040
2,0.027668,0.034667,0.015557,0.005182,0.059439,0.047539,0.016233,0.070575,0.006830,-0.039830,...,0.114422,-0.013504,-0.004343,-0.005034,0.001847,-0.007111,0.075959,0.008050,0.018330,0.072456
3,-0.049505,0.044249,-0.085403,-0.015457,-0.007647,-0.018135,-0.003052,0.020355,-0.032147,-0.043342,...,-0.058308,0.060193,0.040579,-0.046835,-0.055323,0.094035,-0.017977,0.018738,0.017395,0.048383
4,-0.091977,0.032123,-0.028819,-0.004195,0.014297,0.005018,0.019205,-0.067136,0.024127,0.019334,...,-0.007596,-0.034530,0.011921,0.002243,0.024777,-0.017084,0.075972,0.007389,-0.043788,0.008372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,-0.037062,-0.004760,-0.007037,0.010172,0.091438,0.028341,-0.010213,0.019324,-0.016995,0.019922,...,0.037886,-0.039610,-0.035654,0.054998,-0.016989,-0.020845,-0.014195,-0.116977,-0.035451,-0.036397
1549,0.039799,0.024902,0.030050,-0.003333,0.114253,0.018843,-0.008441,-0.003123,-0.035009,-0.081333,...,0.056039,-0.057539,0.003783,0.008777,-0.016449,-0.046382,0.042609,-0.013658,-0.051481,0.004484
1550,-0.017441,0.042004,0.029401,-0.003589,0.015847,-0.046588,0.030215,0.006700,-0.037168,-0.060393,...,0.025725,-0.012143,-0.020829,-0.002537,0.039358,-0.012664,-0.013103,-0.053558,-0.020364,-0.002769
1551,-0.034426,0.029629,-0.010071,0.009321,0.040725,0.039847,-0.046141,-0.016139,-0.002155,-0.006388,...,0.008578,0.087096,-0.038280,-0.000742,0.021201,-0.034627,-0.007643,-0.057122,0.048234,0.051096
1552,-0.042082,-0.000959,-0.032222,-0.007303,0.032690,0.018126,-0.001818,-0.011552,0.008649,0.026969,...,0.044071,-0.012308,0.020689,0.006881,0.028304,-0.044810,-0.009845,-0.051173,-0.006464,0.014150

In [28]:
hdbscan = HDBSCAN(min_cluster_size=2)
hdbscan.fit(embd)

HDBSCAN(min_cluster_size=2)

In [29]:
df_embd['Cluster'] = hdbscan.labels_
df_embd['Cluster'].value_counts()

Cluster
-1      493
 343     18
 143     13
 277     12
 253     12
       ...
 0        2
 23       2
 108      2
 221      2
 66       2
Name: count, Length: 346, dtype: int64

In [30]:
df[(df_embd['Cluster'] == 98).values][['source','category','content']]

        source category                                            content
448  firstpost    world  Lahore: Pakistan's Prime Minister Imran Khan s...
465  firstpost    world  By Umar FarooqIslamabad (Reuters) - Pakistan's...