In [5]:
import surprise

import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases_Rec_Sys\filmtrust\ratings.txt",
                 sep=' ',names=['UserID','ItemID','Rating'])
df.sample(5)

       UserID  ItemID  Rating
21560     896     235     4.0
11710     482       6     2.0
7008      293       7     4.0
32268    1375     254     2.0
4961      205     250     4.0

In [9]:
lowest_rating = df['Rating'].min()
higest_rating = df['Rating'].max()
lowest_rating,higest_rating

(np.float64(0.5), np.float64(4.0))

In [13]:
reader = surprise.Reader(rating_scale=(lowest_rating,higest_rating))
data = surprise.Dataset.load_from_df(df,reader)
type(data)

surprise.dataset.DatasetAutoFolds

## 'user_based': False -> item_based collaborative System

In [32]:
similarity_options = {'name':'cosine','user_based':True} 
algo = surprise.KNNBasic(sim_options = similarity_options, k=70) # default k=40
output = algo.fit(data.build_full_trainset())
# Calculates the  expected ratings for all the users

Computing the cosine similarity matrix...
Done computing similarity matrix.

### Train Test Split

In [33]:
from surprise.model_selection import train_test_split

In [34]:
trainset, testset = train_test_split(data, test_size=0.25, random_state=26)
algo.fit(trainset)

Computing the cosine similarity matrix...
Done computing similarity matrix.

In [35]:
pred = algo.test(testset)
surprise.accuracy.rmse(pred)

RMSE: 0.9282

np.float64(0.9282056050129103)

### Tuning for best k

In [17]:
from surprise.model_selection import GridSearchCV
from surprise.model_selection.split import KFold

In [66]:
param_grid = { 'k':[25,40,50,65,75,85],
             'user_based':[False,True]
             }
kfold = KFold(n_splits=5, random_state=26,shuffle=True)
# gs = GridSearchCV(surprise.KNNBasic, param_grid,measures=['rmse','mae'], cv=kfold)
gs = GridSearchCV(surprise.KNNWithZScore, param_grid,measures=['rmse','mae'], cv=kfold)
gs.fit(data)

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.

In [67]:
print(gs.best_score['rmse'])
print(gs.best_params['rmse'])
print(gs.best_score['mae'])
print(gs.best_params['mae'])

0.82858464566139
{'k': 85, 'user_based': False}
0.6262836041025638
{'k': 85, 'user_based': False}

### Building best model on whole data

In [45]:
algo = gs.best_estimator['rmse']
algo.fit(data.build_full_trainset())

Computing the msd similarity matrix...
Done computing similarity matrix.

In [50]:
a = [2,4,5,7,8,9]
b = [4,7,9]
np.setdiff1d(a,b)  # -> elements of a which not present in b

array([2, 5, 8])

In [51]:
a = [2,4,5,7,8,9]
b = [4,7,9]
np.setdiff1d(b,a)  # -> elements of b which not present in a

array([], dtype=int64)

In [52]:
# Total Numbers of item
ItemID = df['ItemID'].unique()
len(ItemID)

2071

In [58]:
user = 50
u_iid = df[df['UserID'] == user ]['ItemID'].unique()
print('List of item rated by user :\n',u_iid)
print('No. of items rated by user {0} : {1}'.format(user,len(u_iid)))
iids_to_predict = np.setdiff1d(ItemID,u_iid)
print('Items not rated by the user or those items which the expected ratings are to be predicted :\n',iids_to_predict)

List of item rated by user :
 [  8 211   3   2 219 234  12 254 250 207  11 253 236  84  10   7 233  13
   1   5   6 252 241 216 257 206   4 217   9 215 213  17 255 220 121 245
 239 251 235]
No. of items rated by user 50 : 39
Items not rated by the user or those items which the expected ratings are to be predicted :
 [  14   15   16 ... 2069 2070 2071]

In [59]:
testset = [[user,iid,0.] for iid in iids_to_predict]

In [61]:
prediction = algo.test(testset)
prediction

[Prediction(uid=50, iid=np.int64(14), r_ui=0.0, est=np.float64(1.2275204359673026), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(15), r_ui=0.0, est=np.float64(2.4154514276417527), details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(16), r_ui=0.0, est=np.float64(3.318980358997195), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(18), r_ui=0.0, est=np.float64(3.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(19), r_ui=0.0, est=np.float64(2.544959128065395), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(20), r_ui=0.0, est=np.float64(2.5586669192831555), details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(21), r_ui=0.0, est=np.float64(2.9487719250126854), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(22), r_ui=0.0, est=np.float64(3.091280653950954), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(23), r_ui=0.0, est=np.float64(3.7325102880658436), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(24), r_ui=0.0, est=np.float64(3.4319679105667653), details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(25), r_ui=0.0, est=np.float64(2.5841500980117615), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(26), r_ui=0.0, est=np.float64(3.1624725298016245), details={'actual_k': 13, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(27), r_ui=0.0, est=np.float64(3.382164471342114), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(28), r_ui=0.0, est=np.float64(2.4594095656122636), details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(29), r_ui=0.0, est=np.float64(2.782344301922589), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(30), r_ui=0.0, est=np.float64(3.4554534461910515), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(31), r_ui=0.0, est=np.float64(2.747820012710354), details={'actual_k': 14, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(32), r_ui=0.0, est=np.float64(1.6386166339960795), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(33), r_ui=0.0, est=np.float64(3.5987654320987654), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(34), r_ui=0.0, est=np.float64(2.9999999999999996), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(35), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(36), r_ui=0.0, est=np.float64(0.9158499019882386), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(37), r_ui=0.0, est=np.float64(3.445533464015682), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(38), r_ui=0.0, est=np.float64(2.5871462013194297), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(39), r_ui=0.0, est=np.float64(3.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(40), r_ui=0.0, est=np.float64(2.554466535984318), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(41), r_ui=0.0, est=np.float64(2.9087193460490464), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(42), r_ui=0.0, est=np.float64(3.0190930187746616), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(43), r_ui=0.0, est=np.float64(3.80930546210087), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(44), r_ui=0.0, est=np.float64(3.6362397820163492), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(45), r_ui=0.0, est=np.float64(2.5), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(46), r_ui=0.0, est=np.float64(1.722766732007841), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(47), r_ui=0.0, est=np.float64(2.3928053972853576), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(48), r_ui=0.0, est=np.float64(3.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(49), r_ui=0.0, est=np.float64(2.636239782016349), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(50), r_ui=0.0, est=np.float64(3.4272571265134903), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(51), r_ui=0.0, est=np.float64(3.1794129034717837), details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(52), r_ui=0.0, est=np.float64(3.6561250555909925), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(53), r_ui=0.0, est=np.float64(3.6180257510729614), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(54), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(55), r_ui=0.0, est=np.float64(3.4271551390287347), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(56), r_ui=0.0, est=np.float64(2.8813174732925555), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(57), r_ui=0.0, est=np.float64(2.6722102395277556), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(58), r_ui=0.0, est=np.float64(3.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(59), r_ui=0.0, est=np.float64(3.352048679107947), details={'actual_k': 27, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(60), r_ui=0.0, est=np.float64(3.2360515021459224), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(61), r_ui=0.0, est=np.float64(3.029683562027443), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(62), r_ui=0.0, est=np.float64(2.544959128065395), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(63), r_ui=0.0, est=np.float64(1.629912958858193), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(64), r_ui=0.0, est=np.float64(2.9179695958493648), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(65), r_ui=0.0, est=np.float64(1.9455334640156818), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(66), r_ui=0.0, est=np.float64(3.6180257510729614), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(67), r_ui=0.0, est=np.float64(1.8316998039764771), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(68), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(69), r_ui=0.0, est=np.float64(3.43651663516411), details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(70), r_ui=0.0, est=np.float64(2.473105954832159), details={'actual_k': 13, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(71), r_ui=0.0, est=np.float64(3.6180257510729614), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(72), r_ui=0.0, est=np.float64(2.861383366003921), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(73), r_ui=0.0, est=np.float64(2.7517851150172223), details={'actual_k': 10, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(74), r_ui=0.0, est=np.float64(3.5987654320987654), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(75), r_ui=0.0, est=np.float64(3.118025751072961), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(76), r_ui=0.0, est=np.float64(2.409871244635193), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(77), r_ui=0.0, est=np.float64(2.7724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(78), r_ui=0.0, est=np.float64(2.544959128065395), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(79), r_ui=0.0, est=np.float64(3.4650205761316877), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(80), r_ui=0.0, est=np.float64(2.136239782016349), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(81), r_ui=0.0, est=np.float64(3.293438176950305), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(82), r_ui=0.0, est=np.float64(3.881974248927038), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(83), r_ui=0.0, est=np.float64(2.5591799806940663), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(85), r_ui=0.0, est=np.float64(3.4584633243851117), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(86), r_ui=0.0, est=np.float64(3.5), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(87), r_ui=0.0, est=np.float64(3.2667652197285313), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(88), r_ui=0.0, est=np.float64(2.136239782016349), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(89), r_ui=0.0, est=np.float64(2.7918454935622314), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(90), r_ui=0.0, est=np.float64(2.8971273333571115), details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(91), r_ui=0.0, est=np.float64(3.291446464050058), details={'actual_k': 22, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(92), r_ui=0.0, est=np.float64(2.43525952824578), details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(93), r_ui=0.0, est=np.float64(3.1450592815201364), details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(94), r_ui=0.0, est=np.float64(3.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(95), r_ui=0.0, est=np.float64(3.7275204359673024), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(96), r_ui=0.0, est=np.float64(3.7790989730537836), details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(97), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(98), r_ui=0.0, est=np.float64(3.222766732007841), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(99), r_ui=0.0, est=np.float64(1.544959128065395), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(100), r_ui=0.0, est=np.float64(1.6744829952931364), details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(101), r_ui=0.0, est=np.float64(3.7325102880658436), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(102), r_ui=0.0, est=np.float64(3.6445760003302143), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(103), r_ui=0.0, est=np.float64(3.2360256566140335), details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(104), r_ui=0.0, est=np.float64(2.3454394233434988), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(105), r_ui=0.0, est=np.float64(3.7275204359673024), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(106), r_ui=0.0, est=np.float64(2.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(107), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(108), r_ui=0.0, est=np.float64(2.318801089918256), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(109), r_ui=0.0, est=np.float64(3.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(110), r_ui=0.0, est=np.float64(3.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(111), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(112), r_ui=0.0, est=np.float64(3.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(113), r_ui=0.0, est=np.float64(0.6386166339960795), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(114), r_ui=0.0, est=np.float64(3.2360515021459224), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(115), r_ui=0.0, est=np.float64(3.1062691609835444), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(116), r_ui=0.0, est=np.float64(1.4439754412893326), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(117), r_ui=0.0, est=np.float64(3.6180257510729614), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(118), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(119), r_ui=0.0, est=np.float64(1.6386166339960795), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(120), r_ui=0.0, est=np.float64(3.222766732007841), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(122), r_ui=0.0, est=np.float64(2.3613833660039205), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(123), r_ui=0.0, est=np.float64(2.7835865067701153), details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(124), r_ui=0.0, est=np.float64(1.6930831699803977), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(125), r_ui=0.0, est=np.float64(1.0544665359843182), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(126), r_ui=0.0, est=np.float64(3.8815081516855705), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(127), r_ui=0.0, est=np.float64(2.7393824048831505), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(128), r_ui=0.0, est=np.float64(2.3069168300196026), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(129), r_ui=0.0, est=np.float64(2.9087193460490464), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(130), r_ui=0.0, est=np.float64(2.9184093221918044), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(131), r_ui=0.0, est=np.float64(3.1364981504315663), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(132), r_ui=0.0, est=np.float64(3.5898991565982508), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(133), r_ui=0.0, est=np.float64(3.8662551440329214), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(134), r_ui=0.0, est=np.float64(3.384856630879206), details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(135), r_ui=0.0, est=np.float64(2.030373448520969), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(136), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(137), r_ui=0.0, est=np.float64(2.0912806539509536), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(138), r_ui=0.0, est=np.float64(3.331275720164609), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(139), r_ui=0.0, est=np.float64(3.3819742489270386), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(140), r_ui=0.0, est=np.float64(3.5987654320987654), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(141), r_ui=0.0, est=np.float64(2.9670104614825514), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(142), r_ui=0.0, est=np.float64(3.5111733347692637), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(143), r_ui=0.0, est=np.float64(3.380991362864411), details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(144), r_ui=0.0, est=np.float64(3.7699012838908956), details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(145), r_ui=0.0, est=np.float64(3.2724795640326976), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(146), r_ui=0.0, est=np.float64(2.8617238301670285), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(147), r_ui=0.0, est=np.float64(3.6180257510729614), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(148), r_ui=0.0, est=np.float64(3.040654615161406), details={'actual_k': 19, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(149), r_ui=0.0, est=np.float64(2.054466535984318), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(150), r_ui=0.0, est=np.float64(3.6791426802929634), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(151), r_ui=0.0, est=np.float64(3.2360515021459224), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(152), r_ui=0.0, est=np.float64(3.5000000000000004), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(153), r_ui=0.0, est=np.float64(3.5278969957081547), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(154), r_ui=0.0, est=np.float64(2.5841500980117615), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(155), r_ui=0.0, est=np.float64(3.2360515021459224), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(156), r_ui=0.0, est=np.float64(0.7772332679921591), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(157), r_ui=0.0, est=np.float64(2.9193023352620413), details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(158), r_ui=0.0, est=np.float64(1.8316998039764771), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(159), r_ui=0.0, est=np.float64(2.8478065647121666), details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(160), r_ui=0.0, est=np.float64(3.168378585943424), details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(161), r_ui=0.0, est=np.float64(3.2360515021459224), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(162), r_ui=0.0, est=np.float64(4.0), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(163), r_ui=0.0, est=np.float64(2.5823897431378593), details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(164), r_ui=0.0, est=np.float64(3.8662551440329214), details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=50, iid=np.int64(165), r_ui=0.0, est=np.float64(3.363760217983651), details={'actual_k': 2, 'was_impossible': False}),

In [65]:
exp_rating = [ (prediction[i].iid,prediction[i].est) for i in range(0,len(prediction)) ]
df_rating = pd.DataFrame(exp_rating , columns=['ItemID','Est_Rating'])
df_rating.sort_values('Est_Rating',ascending=False).head(30)

      ItemID  Est_Rating
2014    2054         4.0
814      854         4.0
2009    2049         4.0
827      867         4.0
2005    2045         4.0
786      826         4.0
787      827         4.0
2018    2058         4.0
632      672         4.0
630      670         4.0
1167    1207         4.0
1163    1203         4.0
1937    1977         4.0
1982    2022         4.0
53        68         4.0
1978    2018         4.0
1974    2014         4.0
1169    1209         4.0
1973    2013         4.0
1997    2037         4.0
1175    1215         4.0
1193    1233         4.0
1168    1208         4.0
854      894         4.0
848      888         4.0
1146    1186         4.0
1954    1994         4.0
1948    1988         4.0
1942    1982         4.0
597      637         4.0

# Exercise

In [70]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases_Rec_Sys\ml-100k\u.data",
                 sep='\t',names=['UserId','ItemID','Rating','TS'])
df.sample(5)

       UserId  ItemID  Rating         TS
84764     381     118       1  892697051
65259     622     511       4  882592103
55366     457    1028       3  882393828
18188      62     462       2  879373737
88851     711     958       5  876278721

In [71]:
df.drop('TS',axis=1,inplace=True)

In [72]:
df.sample(2)

       UserId  ItemID  Rating
85753     937     326       1
46766     645     203       4

In [73]:
min_rate = df['Rating'].min()
max_rate = df['Rating'].max()

In [76]:
reader = surprise.Reader(rating_scale=(min_rate,max_rate))
data = surprise.Dataset.load_from_df(df,reader)

In [77]:
param_gird = {
    'k':[25,40,50,60,65,70,85],
    'user_based':[True,False]
}
kfold = KFold(n_splits=5,shuffle=True,random_state=26)
gs = GridSearchCV(surprise.KNNBasic,param_grid,cv=kfold,measures=['rmse','mae'])
gs.fit(data)

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.

In [78]:
print(gs.best_score['rmse'])
print(gs.best_params['rmse'])
print(gs.best_score['mae'])
print(gs.best_params['mae'])

0.9761915086082429
{'k': 25, 'user_based': False}
0.7698381577357556
{'k': 25, 'user_based': False}

In [82]:
model = gs.best_estimator['rmse']
model.fit(data.build_full_trainset())

Computing the msd similarity matrix...
Done computing similarity matrix.

In [83]:
ItemID = df['ItemID'].unique()
len(ItemID)

1682