In [3]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\Faceplate.csv",index_col=0)
df.head()

             Red  White  Blue  Orange  Green  Yellow
Transaction
1              1      1     0       0      1       0
2              0      1     0       1      0       0
3              0      1     1       0      0       0
4              1      1     0       1      0       0
5              1      0     1       0      0       0

In [7]:
df = df.astype(bool)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Red     10 non-null     bool
 1   White   10 non-null     bool
 2   Blue    10 non-null     bool
 3   Orange  10 non-null     bool
 4   Green   10 non-null     bool
 5   Yellow  10 non-null     bool
dtypes: bool(6)
memory usage: 140.0 bytes

In [8]:
itemset = apriori(df,min_support=0.2,use_colnames=True)
itemset

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (White, Red)
6       0.4          (Blue, Red)
7       0.2         (Green, Red)
8       0.4        (White, Blue)
9       0.2      (White, Orange)
10      0.2       (White, Green)
11      0.2   (White, Blue, Red)
12      0.2  (White, Green, Red)